import { Check, ExternalLink, LoaderCircle, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";

export function PhotoDownloadRequestsAdminPanel() {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const load = async () => { setLoading(true); try { const response = await fetch("/api/admin/photo-download-requests", { cache: "no-store", credentials: "same-origin" }); const payload = await response.json(); setRequests(payload.requests || []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const grant = async (request) => { setBusy(request.id); try { const response = await fetch(`/api/admin/photo-download-requests/${encodeURIComponent(request.id)}/grant`, { method: "POST", credentials: "same-origin", headers: { origin: window.location.origin, accept: "application/json" } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Grant failed."); setRequests((items) => items.map((item) => item.id === request.id ? { ...item, status: "granted" } : item)); window.open(payload.whatsappUrl, "_blank", "noopener,noreferrer"); } catch (error) { window.alert(error.message); } finally { setBusy(""); } };
  return <section className="photo-request-admin-card"><div className="admin-table-summary"><strong>{requests.length}</strong><span>photo download requests</span><button type="button" onClick={load}><RefreshCw size={15} /> Refresh</button></div>{loading ? <p className="admin-empty">Loading requests…</p> : requests.length === 0 ? <p className="admin-empty">No photo download requests yet.</p> : <div className="photo-request-table-wrap"><table className="photo-request-table"><thead><tr><th>SMI</th><th>Agent</th><th>Contact</th><th>Received</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><strong>{request.listing_code}</strong><small>{request.listing_title}</small></td><td>{request.requester_name}</td><td>{request.requester_phone}</td><td>{new Date(request.created_at).toLocaleString()}</td><td>{request.status}</td><td>{request.status === "pending" ? <button className="button primary compact" type="button" disabled={busy === request.id} onClick={() => grant(request)}>{busy === request.id ? <LoaderCircle className="spin" size={15} /> : <Check size={15} />} Grant &amp; WhatsApp</button> : <a className="button tertiary compact" href={`/property/${request.listing_slug}`}><ExternalLink size={15} /> View SMI</a>}</td></tr>)}</tbody></table></div>}</section>;
}
