import { agentProfile } from "../src/config/agentProfile.js";
import { formatDate, formatPrice, intentLabels } from "../src/utils/listing.js";
import { galleryPhotoUrl } from "../src/utils/galleryPhoto.js";

const escape = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");

export function renderCatalogueContent(listings, { heading, page = 1, pageCount = 1, total = listings.length } = {}) {
  const cards = listings.map((listing) => {
    const href = `/property/${escape(listing.slug)}?intent=${encodeURIComponent(listing.intent)}`;
    return `<article class="property-card"><a class="property-photo" href="${href}" aria-label="View ${escape(listing.title)}">${listing.photos[0] ? `<span class="watermarked-image"><img src="${escape(galleryPhotoUrl(listing.photos[0]))}" alt="${escape(`${listing.title} in ${listing.location}`)}" loading="lazy"></span>` : '<span class="property-photo-placeholder">Photo coming soon</span>'}<span class="intent intent-${listing.intent.toLowerCase()}">${escape(listing.intent)}<small>${escape(intentLabels[listing.intent])}</small></span>${listing.featured ? '<span class="featured-badge">Featured</span>' : ""}</a><div class="property-content"><div class="property-reference"><span>${escape(listing.displayCode || listing.code)}</span><span class="availability availability-${escape(listing.availability.toLowerCase().replaceAll(" ", "-"))}">${escape(listing.availability)}</span></div><h3><a href="${href}">${escape(listing.title)}</a></h3><p class="property-location">${escape(listing.location)}</p><strong class="property-price">${escape(formatPrice(listing.price, listing.intent))}</strong>${listing.alternateIntent && listing.alternatePrice != null ? `<p class="property-alternate-offer">Also available to ${listing.alternateIntent === "WTL" ? "rent" : "buy"}: <strong>${escape(formatPrice(listing.alternatePrice, listing.alternateIntent))}</strong></p>` : ""}<div class="property-facts"><span>${escape(listing.propertyType)}</span>${listing.bedrooms != null || listing.bathrooms != null ? `<span>${escape(listing.bedrooms ?? "—")}R ${escape(listing.bathrooms ?? "—")}B</span>` : ""}${listing.builtUpSqFt ? `<span>${escape(listing.builtUpSqFt.toLocaleString())} sq ft</span>` : ""}</div><div class="property-meta"><span>${escape(listing.furnishing)}</span><span>${listing.listedAt ? "Listed" : "Recorded"} ${escape(formatDate(listing.listedAt || listing.createdAt))}</span></div></div><div class="property-actions view-only"><a class="button secondary" href="${href}">View Details</a></div></article>`;
  }).join("");
  const pages = Array.from({ length: pageCount }, (_, index) => `<a class="button ${index + 1 === page ? "primary" : "secondary"}" href="/catalogue/page/${index + 1}/"${index + 1 === page ? ' aria-current="page"' : ""}>${index + 1}<span class="sr-only">${index + 1 === page ? " (current page)" : " — catalogue page"}</span></a>`).join("");
  return `<div class="site-shell static-catalogue"><header class="site-header"><div class="page-width header-inner"><a class="brand-link" href="/"><img src="/propertydealdesk-mark.png" alt=""><span><strong>${escape(agentProfile.brandName)}</strong><small>HS Ong · ${escape(agentProfile.title)}</small></span></a><nav aria-label="Main navigation"><a class="active" href="/">Properties</a><a href="/inquiries">Find a Property</a><a class="nav-agent-tools" href="https://agenttools.myeviv.com/">Agent Tools</a></nav></div></header><main class="page-width home-stack"><a class="catalogue-back-link" href="/">← Back to Catalogue</a><section class="catalogue-section"><div class="section-heading"><div><span class="eyebrow">Public property listings</span><h1>${escape(heading)}</h1><p>Properties for sale and rent in Klang Valley, listed by HS Ong, Real Estate Negotiator at The Roof Realty Sdn Bhd.</p></div><div class="catalogue-count"><strong>${total}</strong><span>properties · Page ${page} of ${pageCount}</span></div></div><div class="property-grid">${cards}</div><nav class="catalogue-pagination" aria-label="Catalogue pages">${page > 1 ? `<a class="button secondary" rel="prev" href="/catalogue/page/${page - 1}/">← Previous</a>` : ""}${pages}${page < pageCount ? `<a class="button secondary" rel="next" href="/catalogue/page/${page + 1}/">Next →</a>` : ""}</nav><div class="load-more"><a class="button tertiary" href="/">Search and filter properties</a></div></section></main><footer class="site-footer"><div class="page-width footer-grid"><div><strong>${escape(agentProfile.websiteTitle)}</strong><p>${escape(agentProfile.title)}</p></div><div class="footer-links"><a href="/">Properties</a><a href="/inquiries">Find a Property</a><a href="/cmi">CMI Units</a><a class="footer-admin-link" href="/admin/inquiries">Inquiry Admin</a></div><p class="footer-disclaimer">Property information is provided for general reference and is subject to confirmation, availability and change without notice.</p></div></footer></div>`;
}
